### ISSUE TITLE
test whole sequence ?

### ISSUE THREAD

**Issue by ghost** [m-tassano/dvdnet#1]
I had a test sequence which has 8000 frames and i store the image sequences in test folder. When i set the parameter “max_num_fr_per_seq” = 8000 ，The script does not generate work

**Comment by mtassano-gpfw** [comment]
Hi, what was the error you got? 

My guess is that the algorithm tries to load the whole sequence on GPU, and most likely it doesn't have enough memory to load all the images. You can try running the algorithm on CPU by passing "--no_gpu". 

Else, you can try finding the maximum number of frames N_max that can be denoised on your GPU, and make a script which splits the 8000 frames into smaller sequences of N_max frames and denoises these instead of the whole sequence. 

Hope this helps.
Matias

**Comment by Shuai-Yuan-sjtu** [comment]
where is the training codes please?

**Comment by cnscc** [comment]
Could you provide me with the training code? Thank you

**Comment by m-tassano** [comment]
Please see https://github.com/m-tassano/dvdnet/issues/2.
Rgds
